import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    alias(libs.plugins.kotlinMultiplatform)
    alias(libs.plugins.androidLibrary)
    `maven-publish`
}

group = "com.jaidensiu"
version = providers.gradleProperty("libraryVersion").getOrElse("0.1.0-SNAPSHOT")

val generatedVersionDir = layout.buildDirectory.dir("generated/version/kotlin")

val generateCatalogVersion by tasks.registering {
    description = "Generates CatalogVersion.kt, exposing CATALOG_VERSION from the libraryVersion Gradle property."
    group = "build"
    val outputDir = generatedVersionDir
    val versionValue = version.toString()
    outputs.dir(outputDir)
    doLast {
        val file = outputDir.get().file("com/jaidensiu/orbit/catalog/CatalogVersion.kt").asFile
        file.parentFile.mkdirs()
        file.writeText(
            """
            package com.jaidensiu.orbit.catalog

            // Generated by :catalog's generateCatalogVersion task from the `libraryVersion` Gradle property. Do not edit.
            public const val CATALOG_VERSION: String = "$versionValue"

            """.trimIndent() + "\n",
        )
    }
}

kotlin {
    jvmToolchain(17)

    androidTarget {
        publishLibraryVariants("release")
        compilerOptions {
            jvmTarget.set(JvmTarget.JVM_17)
        }
    }

    iosArm64()
    iosSimulatorArm64()
    iosX64()

    sourceSets {
        commonMain {
            kotlin.srcDir(generateCatalogVersion)
        }
        commonTest.dependencies {
            implementation(libs.kotlin.test)
        }
    }
}

android {
    namespace = "com.jaidensiu.orbit.catalog"
    compileSdk = 35

    defaultConfig {
        minSdk = 23
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
}

publishing {
    repositories {
        maven {
            name = "GitHubPackages"
            url = uri("https://maven.pkg.github.com/jaidensiu/orbit")
            credentials {
                username = providers.gradleProperty("gpr.user")
                    .orElse(providers.environmentVariable("GITHUB_ACTOR"))
                    .getOrElse("")
                password = providers.gradleProperty("gpr.token")
                    .orElse(providers.environmentVariable("GITHUB_TOKEN"))
                    .getOrElse("")
            }
        }
    }
}

afterEvaluate {
    (publishing.publications.getByName("androidRelease") as MavenPublication).artifactId = "catalog"
}
